# This Makefile has been generated by the packaging/configure script. DO NOT
# modify it manually. If you want to modify the Makefile model, modify the
# packaging/Makefile.in file
NAME=doctrine-licensemanager
VERSION=1.0
MAINTAINER=Benjamin Eberlei <kontakt@beberlei.de>
PACKAGENAME=doctrine-licensemanager
PACKAGETYPE=deb
URL=http://www.doctrine-project.org
ARCH=all
DEPENDS=-d apache2 -d libapache2-mod-php5
MAINTAINER=Benjamin Eberlei <kontakt@beberlei.de>
DESCRIPTION=Doctrine LicenseManager
POSTINST=--post-install $(PTMP)/src/templates/postinst
PREINST=
POSTRM=
PRERM=
TEMPLATEDIR=templates
TMP=/tmp
ENV=
PTMP=$(TMP)/$(PACKAGENAME)

all: package

clean:
	rm -rf $(PTMP)

structure: clean
	mkdir -p $(PTMP)/src $(PTMP)/build $(PTMP)/misc
	rsync -r --exclude packaging --exclude Makefile \
		--exclude packaging_config.php --exclude '.git*' --exclude '.svn' \
		--exclude '.CVS' --exclude "$(TMP)" . $(PTMP)/src

template: structure
	./packaging/template $(PTMP)/src/$(TEMPLATEDIR) $(ENV)

build: template
	mkdir -p $(PTMP)/build/var/www/doctrine-licensemanager
	mkdir -p $(PTMP)/build/etc/apache2/sites-enabled
	rsync -a --exclude app/logs --exclude app/cache  $(PTMP)/src/* $(PTMP)/build/var/www/doctrine-licensemanager
	rsync -a  $(PTMP)/src/etc/dlm-vhost $(PTMP)/build/etc/apache2/sites-enabled

package: build
	php app/console --env=prod assetic:dump
	fpm -s dir -t $(PACKAGETYPE) -n "$(PACKAGENAME)" -v "$(VERSION)" -m "$(MAINTAINER)" --url "$(URL)" \
		--description "$(DESCRIPTION)" $(DEPENDS) $(POSTINST) $(PREINST) $(POSTRM) $(PRERM) \
		-a $(ARCH) -C $(PTMP)/build -p $(PTMP)/$(PACKAGENAME)_$(VERSION).$(PACKAGETYPE)

