DoctrineLicenseManagerBundle:
    resource: "@DoctrineLicenseManagerBundle/Controller/"
    type:     annotation
    prefix:   /

_welcome:
    pattern: /{path}
    defaults:
        _controller: DoctrineLicenseManagerBundle:Default:index
    requirements:
        path: .*
