#!/bin/sh
mkdir -p /var/www/doctrine-licensemanager/app/cache
mkdir -p /var/www/doctrine-licensemanager/app/logs

chown www-data.www-data /var/www/doctrine-licensemanager -R
chmod 0770 /var/www/doctrine-licensemanager/app/cache
chmod 0770 /var/www/doctrine-licensemanager/app/logs

cd /var/www/doctrine-licensemanager
cp /var/www/doctrine-licensemanager/app/config/parameters_prod.yml /var/www/doctrine-licensemanager/app/config/parameters.yml
sudo -u www-data app/console cache:clear --env=prod

